[package]
name = "rust_course"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0.4"
my_proc_macro = { version = "0.1.0", path = "my_proc_macro" }
reqwest = { version = "0.11.20", features = ["json"] }
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["full"] }
